### ISSUE TITLE
App crashes when userId is set: Could not create directory at /tmp/amplitude-identity

### ISSUE THREAD

**Issue by el-fasoh** [amplitude/Amplitude-Kotlin#137]
## Expected Behavior
Application should not crash when a user logs in and setUserId is called

## Current Behavior
The app launches properly when userId is not set. When a user logs in the app crashes:
Stacktrace:
```
  java.io.IOException: Could not create directory at /tmp/amplitude-identity/$default_instance
         at com.amplitude.id.utilities.FileUtilsKt.createDirectory(FileUtils.kt:9)
         at com.amplitude.id.FileIdentityStorage.<init>(FileIdentityStorage.kt:21)
         at com.amplitude.id.FileIdentityStorageProvider.getIdentityStorage(FileIdentityStorage.kt:71)
         at com.amplitude.core.Amplitude$build$built$1.invokeSuspend(Amplitude.kt:105)
         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
```

## Steps to Reproduce
1. Invoke `amplitude.setUserId(YOUR_ID)`

## Environment
- Device: Google Pixel 7 Pro
- Device OS and Version:  Android Version 13

**Comment by Mercy811** [comment]
Hi @el-fasoh, we'd recommend to follow our [example project](https://github.com/amplitude/Amplitude-Kotlin/tree/c4225f439059e811f748836237c1fde33d6ae01d/samples/kotlin-android-app) to [set user id](https://github.com/amplitude/Amplitude-Kotlin/blob/c4225f439059e811f748836237c1fde33d6ae01d/samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/MainApplication.kt#L64). It works well on my local. 

Could you give more details like environment settings if the example project still fails.

**Comment by el-fasoh** [comment]
Hi @Mercy811 after looking at the sample I notice there are two Amplitude classes in the SDK
`com.amplitude.android.Amplitude` and `com.amplitude.core.Amplitude`. My setup was using the one from core and that was causing crashes.
