### ISSUE TITLE
IllegalArgumentException at AndroidNetworkListener.setupNetworkCallback

### ISSUE THREAD

**Issue by shawn-lin-013** [amplitude/Amplitude-Kotlin#220]
```
Fatal Exception: java.lang.IllegalArgumentException: Too many NetworkRequests filed
       at android.os.Parcel.readException(Parcel.java:1687)
       at android.os.Parcel.readException(Parcel.java:1636)
       at android.net.IConnectivityManager$Stub$Proxy.listenForNetwork(IConnectivityManager.java:2375)
       at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:2790)
       at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:3009)
       at com.amplitude.android.utilities.AndroidNetworkListener.setupNetworkCallback(AndroidNetworkListener.kt:59)
       at com.amplitude.android.utilities.AndroidNetworkListener.startListening(AndroidNetworkListener.kt:32)
       at com.amplitude.android.plugins.AndroidNetworkConnectivityCheckerPlugin.setup(AndroidNetworkConnectivityCheckerPlugin.kt:42)
       at com.amplitude.core.platform.Timeline.add(Timeline.kt:23)
       at com.amplitude.core.Amplitude.add(Amplitude.kt:465)
       at com.amplitude.android.Amplitude.buildInternal$suspendImpl(Amplitude.kt:61)
       at com.amplitude.android.Amplitude.buildInternal(Amplitude.kt:1)
       at com.amplitude.core.Amplitude$build$built$1.invokeSuspend(Amplitude.kt:114)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
        
```

## Environment
- Amplitude SDK Version: 1.16.7

**Comment by yogarunner** [comment]
We are seeing a large number of crashes caused by ```android.net.ConnectivityManager$TooManyRequestsException``` in our latest releases after updating to the new ```Amplitude-Kotlin SDK``` (Version: ```1.16.7```), which seems related to this issue.

We will try disabling ```Offline``` mode for now to hopefully prevent these crashes.
https://amplitude.com/docs/sdks/analytics/android/android-kotlin-sdk#offline-mode

**Comment by izaaz** [comment]
Thanks for raising this folks. Taking a look.

**Comment by izaaz** [comment]
@yogarunner @shawn-lin-013 - do you have a way of reproducing this issue?

**Comment by yogarunner** [comment]
> @yogarunner @shawn-lin-013 - do you have a way of reproducing this issue?

I tried last week but was unable to find a reliable way to reproduce the crashes we are seeing in prod.

**Comment by shawn-lin-013** [comment]
> @yogarunner @shawn-lin-013 - do you have a way of reproducing this issue?

Hi @izaaz, We can't reproduce the issue either. 😢

**Comment by izaaz** [comment]
Thanks @yogarunner @shawn-lin-013. We've added a try catch around the network connectivity listener so it should at least not cause any crashes. Thanks for reporting the issue!
