### ISSUE TITLE
com.amplitude.core.utilities.HttpClient.upload has err with ssl verfiled

### ISSUE THREAD

**Issue by goggeryang** [amplitude/Amplitude-Kotlin#230]
Error when uploading event: Hostname api2.amplitude.com not verified:
11-26 18:55:01.148  4214  4407 E Amplitude:     certificate: sha1/rlMXejjF8DjBT32EKVBoqBRWDPk=
11-26 18:55:01.148  4214  4407 E Amplitude:     DN: CN=prod.byu-pathway.psdops.com
11-26 18:55:01.148  4214  4407 E Amplitude:     subjectAltNames: [prod.byu-pathway.psdops.com, *.origin.prod.byu-pathway.psdops.com, *.prod.byu-pathway.psdops.com]
11-26 18:55:01.148  4214  4407 E Amplitude: Stack trace: javax.net.ssl.SSLPeerUnverifiedException: Hostname api2.amplitude.com not verified:
11-26 18:55:01.148  4214  4407 E Amplitude:     certificate: sha1/rlMXejjF8DjBT32EKVBoqBRWDPk=
11-26 18:55:01.148  4214  4407 E Amplitude:     DN: CN=prod.byu-pathway.psdops.com
11-26 18:55:01.148  4214  4407 E Amplitude:     subjectAltNames: [prod.byu-pathway.psdops.com, *.origin.prod.byu-pathway.psdops.com, *.prod.byu-pathway.psdops.com]
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:205)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.amplitude.core.utilities.HttpClient.upload(HttpClient.kt:23)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at com.amplitude.core.platform.EventPipeline$upload$1.invokeSuspend(EventPipeline.kt:137)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-26 18:55:01.148  4214  4407 E Amplitude: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

**Comment by ablack13** [comment]
@goggeryang Hi there 
Did you solve this issue? I am facing the same behavior

**Comment by izaaz** [comment]
@goggeryang - it looks like the traffic is going thru some proxy? This `DN: CN=prod.byu-pathway.psdops.com` is not an Amplitude domain/cert.
