### ISSUE TITLE
LeakedClosableViolation when initializing Amplitude instance on Android

### ISSUE THREAD

**Issue by mhernand40** [amplitude/Amplitude-Kotlin#54]
The Android project I am working on reports Strict Mode violations as non-fatal errors. One of the non-fatals we are seeing is caused by a `LeakedClosableViolation` when initializing `Amplitude`.

```
java.lang.Throwable: Explicit termination method 'close' not called
    at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:295)
    at dalvik.system.CloseGuard.open(CloseGuard.java:263)
    at java.io.FileInputStream.<init>(FileInputStream.java:176)
    at com.amplitude.id.utilities.PropertiesFile.load
    at com.amplitude.id.FileIdentityStorage.<init>(SourceFile:23)
    at com.amplitude.id.FileIdentityStorageProvider.getIdentityStorage
    at com.amplitude.id.IdentityContainer.<init>(SourceFile:28)
    at com.amplitude.id.IdentityContainer.<init>(SourceFile:0)
    at com.amplitude.id.IdentityContainer$Companion.getInstance
    at com.amplitude.android.Amplitude.build(SourceFile:30)
    at com.amplitude.core.Amplitude.<init>(SourceFile:56)
    at com.amplitude.core.Amplitude.<init>(SourceFile:37)
    at com.amplitude.core.Amplitude.<init>(SourceFile:62)
    at com.amplitude.android.Amplitude.<init>(SourceFile:19)
```

## Expected Behavior
Invoking the `Amplitude` constructor should not throw any strict mode violations on Android.

## Current Behavior
Invoking the `Amplitude` constructor throws a `LeakedClosableViolation` on Android if [detectLeakedClosableObjects](https://developer.android.com/reference/android/os/StrictMode.VmPolicy.Builder#detectLeakedClosableObjects()) is enabled.

## Possible Solution
None

**Comment by yuhao900914** [comment]
Thanks for using Amplitude-Kotlin SDK. Looking at that issue now.

**Comment by yuhao900914** [comment]
Closed this issue. It has been fixed in this [pr](https://github.com/amplitude/Amplitude-Kotlin/pull/56).
