### ISSUE TITLE
Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property isBuilt has not been initialized

### ISSUE THREAD

**Issue by mahmoudElfeel67** [amplitude/Amplitude-Kotlin#73]
## Steps to Reproduce
Dont know but here is the crash report
`Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property isBuilt has not been initialized
       at com.amplitude.core.Amplitude.isBuilt(Amplitude.kt:53)
       at com.amplitude.core.Amplitude$setDeviceId$1.invokeSuspend(Amplitude.kt:188)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)`

## Environment
- android  Version:  v1.3.0 
- Device: iPOCO X3 NFC , Galaxy A32 
- Device OS and Version: E.g. android 11 , android 12

**Comment by EmanHylooz** [comment]
any news on this ?

**Comment by bohan-amplitude** [comment]
Hi @EmanHylooz @mahmoudElfeel67 I'm working on fix for this issue. Do you have any steps I can reproduce the issue so I can test if the fix work?

**Comment by bohan-amplitude** [comment]
Hi @EmanHylooz I released a new version 1.4.3. Changed the lateinit isBuilt to be initialized in init block. The PR is https://github.com/amplitude/Amplitude-Kotlin/pull/81. This should fix the `lateinit property isBuilt has not been initialized` issue. Please checkout the new version and let me know if you have any other questions. Thank you for your feedback.
