### ISSUE TITLE
DiskReadViolation on Android with version 1.4.6

### ISSUE THREAD

**Issue by mhernand40** [amplitude/Amplitude-Kotlin#88]
## Expected Behavior
Initializing Amplitude on the main thread should not trigger a strict mode violation.

## Current Behavior
As of 1.4.6, initializing Amplitude on the main thread triggers a `DiskReadViolation`.

## Environment
- Device: Pixel 5a
- Device OS and Version: Android 12

## Stack Trace
```
Process: io.opensea.debug, PID: 13914
java.lang.RuntimeException: StrictMode ThreadPolicy violation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1876)
	at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$handleViolationWithTimingAttempt$0$StrictMode$AndroidBlockGuardPolicy(StrictMode.java:1790)
	at android.os.StrictMode$AndroidBlockGuardPolicy$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.os.strictmode.DiskReadViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
	at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7747)
	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
	at java.io.File.exists(File.java:813)
	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:751)
	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:742)
	at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:698)
	at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:923)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:545)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:196)
	at com.amplitude.android.utilities.AndroidStorage.<init>(AndroidStorage.kt:32)
	at com.amplitude.android.utilities.AndroidStorageProvider.getStorage(AndroidStorage.kt:106)
	at com.amplitude.android.Amplitude.<init>(Amplitude.kt:33)
```

**Comment by mhernand40** [comment]
This is the culprit:
https://github.com/amplitude/Amplitude-Kotlin/commit/e4f9874f60fe82ea1edbf9c8d76335c7def2581d#diff-f0db7176910d8c66beb88e8beb06441160b470c3733061f319a17622f1afcfd6R33

**Comment by mhernand40** [comment]
Just updated to `1.4.8` and confirmed that this issue has been resolved. Thank you! 🙂
